### PR TITLE
HDMIDisplay module done!

### PR DESCRIPTION
**Pull request by hrpccs**
There is a HDMIDisplay module for Pynq-Z1 and now yatcpu supports the command line operations for basys3 and Pynq-Z1 separately (check Makefile for details)

### CODE REVIEW

**Comment by howardlau1999** [comment]
Please remove all the generated .txt files and format all the .scala files

**Comment by hrpccs** [comment]
> 

what does formating the .scala files mean?
the coding style? or something?

**Comment by howardlau1999** [comment]
just run "reformat code" in your IDE

**Comment by hrpccs** [comment]
> just run "reformat code" in your IDE
I have reformated my .scala files and deleted the .txt files now. The .v files is necessary.

**Pull request merged**
